TARGET_LD = ld
TARGET_OBJCOPY = objcopy


KERNEL_OBJECTS := Boot/boot.o Kernel/kernel.o  \
					lib/lib.o

all:kernel

LD_FLAGS := -Map System.map --force-exe-suffix \
	-nostdlib -TLink.ld

OBJCOPY_FLAGS := -R .dynamic -R .note -R .comment -S -O binary
 

Boot/boot.o:
	@ (cd Boot;make)

Kernel/kernel.o:
	@ (cd Kernel;make)

lib/lib.o:
	@ (cd lib;make)

kernel:kernel.exe
	@ $(TARGET_OBJCOPY) $(OBJCOPY_FLAGS)  $< $@

kernel.exe:$(KERNEL_OBJECTS)
	@ $(TARGET_LD) $(LD_FLAGS) -o$@ $^

install: 
	@ echo "mounting floppy image..." 
	@ mount -o loop floppy.img /mnt 
	@ echo "copy kernel to floppy..."
	@ \cp kernel /mnt/	
	@	sync
	@ echo "unmounting floppy..."
	@ umount /mnt	
	@ echo "OK"	
	
dep:
	gcc -MM -I./Include Kernel/*.c | sed 's/\.c/.c/g' >> Makefile
	(cd Kernel;make depend)


clean:
	(cd Kernel;make clean)
	(cd Boot;make clean)
	(cd lib;make clean)
	(\rm -rf *.bin *.exe  *~ System.map kernel)
	
	
	
############
#dependencies generated by
#gcc -MM -I../Include *.c | sed 's/\.c/.c/g' >> Makefile
############
main.o: Kernel/main.c Include/kernel/console.h Include/kernel/types.h
console.o: Kernel/console.c Include/kernel/console.h \
 Include/kernel/types.h
main.o: Kernel/main.c Include/kernel/console.h Include/kernel/types.h
console.o: Kernel/console.c Include/kernel/console.h \
 Include/kernel/types.h Include/string.h Include/kernel/types.h \
 Include/asm/io.h Include/asm/system.h Include/kernel/page.h \
 Include/kernel/kernel.h Include/kernel/mm.h Include/kernel/multiboot.h
ide.o: Kernel/ide.c Include/kernel/ide.h Include/kernel/types.h \
 Include/asm/io.h Include/kernel/kernel.h Include/string.h \
 Include/kernel/types.h
idt.o: Kernel/idt.c Include/kernel/kernel.h Include/kernel/idt.h \
 Include/kernel/types.h
keyboard.o: Kernel/keyboard.c Include/asm/io.h Include/kernel/types.h \
 Include/kernel/keyboard.h Include/kernel/kernel.h
kthread.o: Kernel/kthread.c Include/kernel/kthread.h \
 Include/kernel/types.h Include/kernel/segment.h Include/kernel/kernel.h \
 Include/list.h Include/kernel/mm.h Include/kernel/multiboot.h \
 Include/string.h Include/kernel/types.h Include/kernel/page.h \
 Include/unistd.h Include/kernel/tss.h
main.o: Kernel/main.c Include/kernel/console.h Include/kernel/types.h \
 Include/string.h Include/kernel/types.h Include/asm/system.h \
 Include/kernel/segment.h Include/kernel/kernel.h Include/kernel/mm.h \
 Include/kernel/multiboot.h Include/kernel/idt.h Include/kernel/timer.h \
 Include/list.h Include/kernel/keyboard.h Include/kernel/tss.h \
 Include/kernel/kthread.h Include/kernel/ide.h Include/kernel/page.h
mm.o: Kernel/mm.c Include/asm/system.h Include/kernel/types.h \
 Include/kernel/kernel.h Include/kernel/mm.h Include/kernel/multiboot.h
page.o: Kernel/page.c Include/kernel/page.h Include/kernel/kernel.h \
 Include/kernel/mm.h Include/kernel/types.h Include/kernel/multiboot.h \
 Include/string.h Include/kernel/types.h
segment.o: Kernel/segment.c Include/kernel/segment.h \
 Include/kernel/types.h Include/kernel/kernel.h Include/string.h \
 Include/kernel/types.h
syscall.o: Kernel/syscall.c Include/kernel/syscall.h Include/kernel/idt.h \
 Include/kernel/types.h Include/kernel/kernel.h Include/unistd.h \
 Include/kernel/kthread.h Include/kernel/segment.h Include/list.h \
 Include/kernel/timer.h
timer.o: Kernel/timer.c Include/asm/io.h Include/kernel/types.h \
 Include/kernel/timer.h Include/kernel/kernel.h Include/list.h \
 Include/kernel/kthread.h Include/kernel/segment.h
tss.o: Kernel/tss.c Include/kernel/kernel.h Include/kernel/tss.h \
 Include/kernel/types.h Include/kernel/segment.h Include/kernel/mm.h \
 Include/kernel/multiboot.h
